import puppeteer from 'puppeteer';
const browser = await puppeteer.launch({ headless: true, acceptInsecureCerts: true, args: ['--autoplay-policy=no-user-gesture-required', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'], defaultViewport: { width: 1280, height: 800 } });
const page = await browser.newPage();
const errors = [];
page.on('pageerror', (e) => errors.push(e.message));
await page.goto('https://localhost:5173/?input=bot', { waitUntil: 'networkidle0' });
const count = () => page.evaluate(() => { let n = 0; window.__scene?.traverse(() => n++); return n; });
await page.click('#btn-start');
await page.waitForFunction(() => document.querySelector('#hud')?.classList.contains('show'));
await new Promise((r) => setTimeout(r, 2000));
console.log('objects during play #1:', await count());
await page.keyboard.press('Escape');
await new Promise((r) => setTimeout(r, 500));
console.log('objects after stop:', await count());
await page.click('#btn-start');
await page.waitForFunction(() => document.querySelector('#hud')?.classList.contains('show'));
await new Promise((r) => setTimeout(r, 2000));
console.log('objects during play #2:', await count());
console.log(errors.length ? 'page errors: ' + errors.join('; ') : 'no page errors');
await browser.close();
